name: Semantic Versioning and Helm Chart Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release and Attach Helm Chart to GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (required for semantic-release)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run semantic-release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Install Helm
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      # Package the Helm Chart
      - name: Package Helm Chart
        run: |
          helm lint
          helm package .

      # Get the repository name dynamically
      - name: Extract repository name
        run: echo "REPOSITORY_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      # Attach Helm Chart package as a release asset
      - name: Upload Helm Chart as Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.semantic_release.outputs.release_url }}
          asset_path: ${{ env.REPOSITORY_NAME }}.tgz
          asset_name: ${{ env.REPOSITORY_NAME }}.tgz
          asset_content_type: application/gzip
